### ISSUE TITLE
Difficult to tell which things are buttons

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [F1F7Y/Better.Serverbrowser#1]
If possible it would be better to give the buttons an inactive background colour, or outline, or something that makes them stand out from just regular text, more specifically the "DESCRIPTION" and "MODS" buttons don't look like they are buttons

**Comment by F1F7Y** [comment]
For the time being I got rid of   the server description and server mods menu buttons. I am unsure if I want to add an inactive background to the CLEAR and JOIN buttons since it may introduce too many layers and may make it look more cluttered.
Will look into what I can do
