### ISSUE TITLE
Export texts

### ISSUE THREAD

**Issue by Alystrasz** [F1F7Y/Better.Serverbrowser#2]
Hello, and thanks for the mod!

Could you export all of its texts into a located file, just like Northstar client (https://github.com/R2Northstar/NorthstarMods/blob/main/Northstar.Client/mod/resource/northstar_client_localisation_english.txt) ?

It would allow translation of the mod and thus greater usage/integration among players base.

(I'm willing to translate your mod to French btw)

**Comment by F1F7Y** [comment]
My main focus right now is functionality, localisation is already on the list. May even get to it today

**Comment by F1F7Y** [comment]
v1.2.1 now has english localisation
