### ISSUE TITLE
Fix string.find

### ISSUE THREAD

**Issue by 4yre** [F1F7Y/Better.Serverbrowser#5]
I did play around with `string.find` yesterday and it seems it returns first occurrence or `null` if not found (see http://squirrel-lang.org/squirreldoc/reference/language/builtin_functions.html#string)
If you did what I did `if (str.find(subStr)` that would explains why your string.find did only works like 10% of the time.
Tested it and `if (str.find(subStr) != null) { /* filter matched */ }` works perfectly fine for me.

Won't open a PR for this, just leaving it here in case you want to clean up your code.

**Comment by F1F7Y** [comment]
Thanks!
I was using unofficial docs where there was no mention of how the func actually works so I just passed it as broken

Credited you in the mod.json file
