### ISSUE TITLE
Update list on filter text change instead of enter pressed

### ISSUE THREAD

**Issue by 4yre** [F1F7Y/Better.Serverbrowser#6]
Instead of listening for the enter key to filter the displayed servers its possible to use `Hud_AddEventHandler( element, UIE_CHANGE, Callback )` on the text box (found that after some digging in other files).
Could then filter every time the box changes, not only if the user presses enter.
Only concern would be that if the server list is like SUPER long, it might lead to performance issues if its filtered every time the user types a single character into the filter box.

This would also free the enter key for other purposes (like connect to selected server), but I don't think there is a need for that.

Could add that myself, if you want.

**Comment by F1F7Y** [comment]
Already implemented, will be in v1.2.4
