### ISSUE TITLE
Got an error when dragging the scroll bar

### ISSUE THREAD

**Issue by HK560** [F1F7Y/Better.Serverbrowser#9]
I get this error every time I press the scroll bar 
- ver. 1.2.3

![](https://cdn.jsdelivr.net/gh/HK560/MyPicHub@master/res/pic/Snipaste_2021-12-29_10-24-55.jpg)
![](https://cdn.jsdelivr.net/gh/HK560/MyPicHub@master/res/pic/Snipaste_2021-12-29_10-25-07.jpg)

**Comment by HK560** [comment]
It looks like when the number of servers just occupies one page, drag the scroll bar to get this error

**Comment by F1F7Y** [comment]
Thanks, should be fixed in next version
